console.log("Atribuição de Variáveis"); 

const idade = 23; 
const nome = "Vinicius"; 
const sobrenome = "Roque"; 

console.log ( nome + " " + sobrenome); 
console.log (` Meu nome é ${ nome} ${sobrenome}`); 

const nomePessoal = nome + " " + sobrenome; 

console.log(`Meu nome  é ${nomePessoal}`);  

/* OBSERVAÇÕES

- A atribuição LET pode ser mudada durante todo o código, ou seja a mesma variárel pode assumir diversos
valores ao decorrer do seu código. Já o CONST não é possível ser modificado, deixando a variável estáti-
ca durante todo o código. 
*/

